Aamna dev
NeuroDataDesign/pyprep pull request #3
Opened 2019-11-29 20:48 UTC by AamnaLawrence

The updated noisy channels code detects noisy channels by testing them on the basis of deviation, correlation, random sampling consensus, low signal to noise ratio, high-frequency noise, flatness and Nan values. This function is iteratively called when performing robust referencing.
The remove trend function filters the data using high pass and high pass sinc filters. It can also perform local detrending of data using. This function is used in PREP pipeline and iteratively called when performing robust referencing. 
The tests for both the above-mentioned functionalities are also provided. 
@adam2392

2019-12-01 22:10 UTC, adam2392 commented on pyprep/test_find_noisy_channels.py
> +    raw.drop_channels(ch_names=bads)
These should all be in a test function.

2019-12-01 22:11 UTC, adam2392 commented on pyprep/test_removeTrend.py
> +test_detrend()
Same here. These are just called when you run: "pytest ./test/"

2019-12-01 22:11 UTC, adam2392 commented on pyprep/test_find_noisy_channels.py
> +test_find_bad_by_SNR(raw)
Unnecessary.

2019-12-01 22:14 UTC, adam2392 requested changes
Stylistic Changes:

1. Setup of tests: use the "conftest.py" file and pytest fixtures framework. Any setup of data structures can be done in the conftest.py file, and then imported over using pytest fixtures. Google this and see what I mean. We can discuss in person. 
2. Add a "scikit-learn" fit() style function if find_noisy_channels is going to be called and do an entire pipeline with default parameters. If separate functions need to be called, then not needed.

2019-12-03 20:52 UTC, Nick3151 requested changes
Please add the extract EEG data line as mentioned, otherwise it will cause a bug with channel index
Please change the function name as mentioned so I can easily switch between your version and Noisydata

2019-12-03 20:52 UTC, Nick3151 commented on pyprep/find_noisy_channels.py
> +        self.EEGData = self.raw_mne.get_data(picks="eeg")
Extract eeg data here:
self.raw_mne.pick_types(eeg=True, stim=False)

2019-12-03 20:52 UTC, Nick3151 commented on pyprep/find_noisy_channels.py
> +
Please change this function name to find_all_bads so I can easily compare your code with Noisydata

2019-12-10 18:16 UTC, closed without merging